### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'unique_id'

### ISSUE THREAD

**Issue by 2t0m** [crowbarz/ha-pioneer_async#2]
Hi @crowbarz and thanks for your work.

I have a VSX-S510 and I got an error after updating to 0.1 via HACS.

My configuration.yaml
```
media_player:
  - platform: pioneer_async
    host: 192.168.1.123
    sources: { TV: '06', GCast: '15' }
```

Error Log
```
Error while setting up pioneer_async platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_add_entity
    if entity.unique_id is not None:
  File "/config/custom_components/pioneer_async/media_player.py", line 217, in unique_id
    return self._entry.unique_id + "/" + self._zone
AttributeError: 'NoneType' object has no attribute 'unique_id'
```

Debug
```
2020-11-03   16:18:50 DEBUG (MainThread) [custom_components.pioneer_async.pioneer_avr]   Opening AVR connection
2020-11-03 16:18:50 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr]   PioneerAVR.__init__(host="192.168.1.123", port=8102, timeout=2.0,   command_delay=0.1, volume_workaround=False)
2020-11-03 16:18:51 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] >>   PioneerAVR.connection_listener() started
2020-11-03 16:18:51 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?P
2020-11-03 16:18:51 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR connection established
2020-11-03 16:18:51 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Querying available zones on AVR
2020-11-03 16:18:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?P returned   response: PWR2
2020-11-03 16:18:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   PWR2
2020-11-03 16:18:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?AP
2020-11-03 16:18:52 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Zone 1 discovered
2020-11-03 16:18:52 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Zone 1: Power: False
2020-11-03 16:18:54 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?AP returned   response: APR1
2020-11-03 16:18:54 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   APR1
2020-11-03 16:18:54 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?BP
2020-11-03 16:18:54 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Zone 2 discovered
2020-11-03 16:18:54 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Zone 2: Power: False
2020-11-03 16:18:55 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:18:57 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?BP timed out
2020-11-03 16:18:57 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:18:57 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?ZEP
2020-11-03 16:19:01 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?ZEP timed out
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?M returned   response: MUT1
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?P returned   response: PWR2
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?V returned   response: VOL101
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   MUT1
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   PWR2
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   VOL101
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Delaying command for 0.015s
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Delaying command for 0.093s
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?F
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?M
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?P
2020-11-03 16:19:02 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?V
2020-11-03 16:19:02 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Updating AVR status (full=True,   last updated 4.710s ago)
2020-11-03 16:19:02 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Zone 1: Mute: False
2020-11-03 16:19:02 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Zone 1: Volume: 101
2020-11-03 16:19:05 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?F returned   response: FN06
2020-11-03 16:19:05 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   FN06
2020-11-03 16:19:05 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?AP
2020-11-03 16:19:05 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Zone 1: Source: TV
2020-11-03 16:19:06 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?AP returned   response: APR1
2020-11-03 16:19:06 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   APR1
2020-11-03 16:19:06 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?ZV
2020-11-03 16:19:07 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?ZV returned   response: ZV00
2020-11-03 16:19:07 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   ZV00
2020-11-03 16:19:07 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?Z2M
2020-11-03 16:19:07 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Zone 2: Volume: 0
2020-11-03 16:19:08 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?Z2M returned   response: Z2MUT1
2020-11-03 16:19:08 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   Z2MUT1
2020-11-03 16:19:08 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Sending AVR command: ?ZS
2020-11-03 16:19:08 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Zone 2: Mute: False
2020-11-03 16:19:09 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR command ?ZS returned   response: Z2F04
2020-11-03 16:19:09 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   Z2F04
2020-11-03 16:19:09 INFO (MainThread)   [custom_components.pioneer_async.pioneer_avr] Zone 2: Source: 04
2020-11-03 16:19:10 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Skipping update: last updated   0.003s ago
2020-11-03 16:19:10 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Skipping update: last updated   0.004s ago
2020-11-03 16:19:39 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:19:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Skipping update: last updated   12.083s ago
2020-11-03 16:20:09 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:20:39 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:20:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Skipping update: last updated   12.083s ago
2020-11-03 16:21:09 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:21:40 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:21:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Skipping update: last updated   12.084s ago
2020-11-03 16:22:10 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:22:40 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:22:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Skipping update: last updated   12.085s ago
2020-11-03 16:23:10 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:23:40 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:23:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Skipping update: last updated   12.086s ago
2020-11-03 16:24:10 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:24:40 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:24:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Skipping update: last updated   12.085s ago
2020-11-03 16:25:10 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:25:40 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:25:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Skipping update: last updated   12.086s ago
2020-11-03 16:26:10 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:26:40 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:26:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Skipping update: last updated   12.088s ago
2020-11-03 16:27:10 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:27:40 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:27:52 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] Skipping update: last updated   12.084s ago
2020-11-03 16:28:10 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
2020-11-03 16:28:40 DEBUG (MainThread)   [custom_components.pioneer_async.pioneer_avr] AVR listener received response:   R
```

Can you do something to solve this issue ?
Let me know if I can send you more information.

**Comment by crowbarz** [comment]
Hi @2t0m, thanks for reporting the bug.

The integration was trying to use data in a config entry to generate a unique ID for each entity. That config entry is only created if the integration is configured via the UI. As you may have guessed, I don't configure via `configuration.yaml` in my own setup so didn't pick this issue up. I'll test both going forward to hopefully avoid these issues in the future, especially while hard coding sources isn't supported when configured via the UI.

I've fixed this in 0.1.1. Can you try that version and let me know how you go?

**Comment by crowbarz** [comment]
BTW did you add this repository as a custom repository in HACS to get it to install? Curious to know whether that works. I have hacs/default#667 open to get it into HACS default but it hasn't been merged yet. The documentation was written assuming that PR had already been merged.

**Comment by 2t0m** [comment]
I added the repository in HACS and 0.1.1 solves the problem, thanks.

My AVR is not supporting the set_volume_level command but only volume_up and volume_down. May you enable this way to control the volume please ?

**Comment by crowbarz** [comment]
Can you open a new issue for that separate problem? Please include the relevant debug showing the AVR commands and responses when you trigger the HA services.

Closing as the original issue has been resolved.
